### ISSUE TITLE
Availability of the released app?

### ISSUE THREAD

**Issue by maaeedee** [GeoTecINIT/WearOSSensors#5]
Is the possible to make the .apk format of your software available? both for the smartphone and the smartwatch.

**Comment by matey97** [comment]
Hi @maaeedee, I've included the `apk` of the demo application in the [v1.1.0 release](https://github.com/GeoTecINIT/WearOSSensors/releases/tag/v1.1.0). I've also added the `apk` of the smartphone demo application in the [v1.2.1 release](https://github.com/GeoTecINIT/nativescript-wearos-sensors/releases/tag/v1.2.1) on its repository.
